import React from 'react';
import {
  FaCode,
  FaRobot,
  FaGraduationCap,
  FaLightbulb,
  FaChartLine,
  FaKeyboard,
  FaStickyNote,
  FaUserTie
} from 'react-icons/fa';
import { useNavigate } from 'react-router-dom';
import Navbar from './Navbar';
import Footer from './Footer';
import myPhoto from '../assets/images/ww.jpg'

const AboutUs = () => {
  const navigate = useNavigate();
  const features = [
    {
      icon: <FaRobot className="text-3xl text-gray-400" />,
      title: "AI-Powered Roadmaps",
      description: "Get personalized learning paths generated by our advanced AI based on your skills and goals"
    },
    {
      icon: <FaCode className="text-3xl text-gray-400" />,
      title: "Interactive Coding",
      description: "Write, run, and debug code directly in your browser with our built-in IDE"
    },
    {
      icon: <FaGraduationCap className="text-3xl text-gray-400" />,
      title: "Smart Quizzes",
      description: "Test your knowledge with adaptive quizzes that evolve with your learning progress"
    },
    {
      icon: <FaKeyboard className="text-3xl text-gray-400" />,
      title: "Typing Test",
      description: "Measure and improve your typing speed and accuracy with real-time feedback"
    },
    {
      icon: <FaStickyNote className="text-3xl text-gray-400" />,
      title: "Summarize Notes",
      description: "Use AI to instantly generate concise summaries from your long notes for quick revision"
    },
    {
      icon: <FaUserTie className="text-3xl text-gray-400" />,
      title: "Mock Interview",
      description: "Practice job interviews with AI-powered questions tailored to your career goals"
    }
  ];

  const TechStack = [
    'JavaScript', 'Python',
    'React', 'Node.js',
    'Django', 'TypeScript', 'Java',
    'C++', 'Go',
    'Rust', 'SQL',
    'MongoDB'
  ];

  return (
    <>
      <Navbar />
      <div className="mt-9 min-h-screen bg-gray-50">

        {/* Hero Section */}
        <section className="relative py-20 bg-white text-white">
          <div className="container mx-auto px-6 text-center">
            <h1 className="text-gray-900 text-4xl md:text-6xl font-bold mb-6">About Mapito</h1>
            <p className="text-gray-400 text-xl md:text-2xl max-w-3xl mx-auto">
              The intelligent practice platform for developers of all levels
            </p>
          </div>
        </section>

        {/* About our system section */}
        <section className="py-20 bg-white">
          <div className="container mx-auto px-6">
            <div className="flex flex-col md:flex-row items-center">
              <div className="md:w-1/2 mb-10 md:mb-0">
                <h2 className="text-3xl font-bold text-indigo-600 mb-6">Our System</h2>
                <p className="text-gray-600 mb-4">
                  At Mapito, we're revolutionizing how developers learn and practice. We combine AI-powered guidance with
                  hands-on coding experience to create the most effective learning platform.
                </p>
                <p className="text-gray-600 mb-6">
                  Whether you're preparing for interviews, learning new technologies, or sharpening your skills,
                  Mapito provides the tools and structure to help you succeed.
                </p>
              </div>
              <div className="md:w-1/2 md:pl-12">
                <div className="bg-gray-100 p-8 rounded-xl">
                  <div className="grid grid-cols-3 gap-4">
                    {[1, 2, 3, 4, 5, 6].map((item) => (
                      <div key={item} className="bg-white p-4 rounded-lg shadow-md flex flex-col items-center">
                        <div className="w-10 h-10 bg-gray-900 rounded-full flex items-center justify-center mb-2">
                          <FaLightbulb className="text-white" />
                        </div>
                        <span className="text-xs font-medium text-gray-600">Step {item}</span>
                      </div>
                    ))}
                  </div>
                  <div className="mt-6 p-4 bg-gray-900 rounded-lg border border-blue-100">
                    <div className="flex items-center">
                      <div className="w-8 h-8 bg-white rounded-full flex items-center justify-center mr-3">
                        <FaChartLine className="text-gray-900 text-sm" />
                      </div>
                      <div>
                        <p className="text-sm font-medium text-white">AI-generated learning path</p>
                        <p className="text-xs text-white">Provide from a roadmap to interview stage</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Features */}
        <section className="py-20 bg-gray-100">
          <div className="container mx-auto px-6">
            <h2 className="text-3xl font-bold text-center text-gray-800 mb-16">How Mapito Helps You Grow</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
              {features.map((feature, index) => (
                <div key={index} className="bg-white p-8 rounded-xl shadow-lg hover:shadow-xl transition duration-300">
                  <div className="flex justify-center mb-4">
                    {feature.icon}
                  </div>
                  <h3 className="text-xl font-bold mb-3 text-center text-gray-900">{feature.title}</h3>
                  <p className="text-gray-600 text-center">
                    {feature.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Team section */}
        <section className="bg-white py-16 px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto">
            {/* Section Header */}
            <div className="text-center mb-12">
              <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
                Our Team
              </h1>
              <h2 className="text-xl sm:text-2xl text-gray-600">
                Meet the People Behind <span className='text-indigo-600'>Mapito</span>
              </h2>
              <p className="mt-4 text-gray-600 max-w-2xl mx-auto">
                Our team brings together educators, tech lovers, and problem-solvers who care about making education easier for everyone.
              </p>
            </div>

            {/* Team Members */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              {/* Member 1 */}
              <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm hover:shadow-md transition-shadow duration-300 hover:border-indigo-500">
                <div className="flex items-start space-x-4">
                  <div className="flex-shrink-0">
                    <img
                      src={myPhoto}
                      alt="Wint Wah Kyaw Soe"
                      className="w-16 h-16 rounded-full object-cover"
                    />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-gray-900">Wint Wah Kyaw Soe</h3>
                    <p className="text-indigo-600 font-medium mb-2">Founder & Developer of Mapito</p>
                    <p className="text-gray-600">
                      You can call me 'Shi' and I love coffee with coding. I describe myself as a person full of desire
                      to learn. I am a fullstack developer and global learning enthusiast. I usually waste my time by exploring
                      opportunities and learning new things.
                    </p>
                  </div>
                </div>
              </div>

              {/* Member 2 */}
              <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm hover:shadow-md transition-shadow duration-300 hover:border-indigo-500">
                <div className="flex items-start space-x-4">
                  <div className="flex-shrink-0">
                    <img
                      src="https://i.pinimg.com/736x/02/59/54/0259543779b1c2db9ba9d62d47e11880.jpg"
                      alt="Another Member"
                      className="w-16 h-16 rounded-full object-cover"
                    />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-gray-900">Team member 2</h3>
                    <p className="text-indigo-600 font-medium mb-2">Upcoming</p>
                    <p className="text-gray-600">
                      Passionate about design and storytelling. I turn ideas into visual experiences and enjoy creating things that feel good and look better.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Tech Stack */}
        <section className="py-20 bg-white">
          <div className="container mx-auto px-6">
            <h2 className="text-3xl font-bold text-center text-gray-800 mb-6">Supported Technologies</h2>
            <p className="text-xl text-gray-600 text-center max-w-2xl mx-auto mb-16">
              Practice with the most in-demand technologies and frameworks
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 gap-6">
              {TechStack.map((tech) => (
                <div key={tech} className="bg-indigo-100 p-4 rounded-lg border border-gray-200 flex items-center justify-center hover:border-blue-300 transition duration-300">
                  <span className="font-medium text-gray-700">{tech}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* banner */}
        <section className="py-20 bg-white">
          <div className="container mx-auto px-6 text-center">
            <h2 className="text-3xl font-bold text-gray-800 mb-6">Ready to Accelerate Your Coding Skills?</h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto mb-8">
              Join thousands of developers who use Mapito to practice smarter and grow faster.
            </p>
            <button onClick={() => navigate("/home")} className="px-8 py-4 bg-indigo-600 text-white rounded-lg transition duration-300 text-lg font-semibold cursor-pointer">
              Start Your Journey Now
            </button>
          </div>
        </section>
      </div>

      {/* footer */}
      <Footer />
    </>
  );
};

export default AboutUs;
